from __future__ import annotations

DEMO_ERRORS = [
    {
        "date": "2026-05-04",
        "project": "Taxi Demand Forecasting",
        "ml_type": "Time Series",
        "topic": "Feature Engineering",
        "algorithm": "pandas / sklearn",
        "error_type": "KeyError",
        "mistake": "Used data['lag_1'] before the lag feature was created.",
        "cause": "The feature creation function was not executed before selecting columns for training.",
        "fix": "Run make_features() before splitting features and target; check df.columns before selecting lag columns.",
        "practice_task": "Create lag_1, lag_2, lag_24 with shift() on a small time-series dataframe and verify columns before model training.",
        "status": "Need Practice",
        "difficulty": "Easy",
        "next_review_date": "2026-05-05",
    },
    {
        "date": "2026-05-04",
        "project": "Customer Churn Prediction",
        "ml_type": "Supervised Learning",
        "topic": "Data Leakage",
        "algorithm": "StandardScaler / LogisticRegression",
        "error_type": "Data Leakage",
        "mistake": "Applied StandardScaler to the full dataset before train/test split.",
        "cause": "Information from the test set leaked into the training process through preprocessing.",
        "fix": "Split data first, then fit the scaler only on X_train; use Pipeline to avoid leakage.",
        "practice_task": "Build a sklearn Pipeline with StandardScaler and LogisticRegression and compare it with the incorrect full-data scaling approach.",
        "status": "Need Practice",
        "difficulty": "Hard",
        "next_review_date": "2026-05-06",
    },
    {
        "date": "2026-05-04",
        "project": "Energy Consumption Forecasting",
        "ml_type": "Time Series",
        "topic": "Train/Test Split",
        "algorithm": "train_test_split",
        "error_type": "Wrong Split",
        "mistake": "Used shuffle=True for a time-series split.",
        "cause": "Random shuffling breaks chronological order and makes future data influence training.",
        "fix": "Use shuffle=False or split by index/date; train on earlier data and test on later data.",
        "practice_task": "Split a time-series dataset into 90% train and 10% test without shuffling and plot both periods.",
        "status": "Need Practice",
        "difficulty": "Medium",
        "next_review_date": "2026-05-05",
    },
    {
        "date": "2026-05-04",
        "project": "Bank Client Classification",
        "ml_type": "Supervised Learning",
        "topic": "Metrics",
        "algorithm": "LogisticRegression",
        "error_type": "Wrong Metric",
        "mistake": "Used accuracy as the main metric for an imbalanced classification task.",
        "cause": "Accuracy can look high when the model mostly predicts the majority class.",
        "fix": "Check class balance and use precision, recall, F1-score, ROC-AUC or PR-AUC depending on the task.",
        "practice_task": "Create an imbalanced dataset and compare accuracy, precision, recall and F1 for a dummy classifier and logistic regression.",
        "status": "Practiced",
        "difficulty": "Medium",
        "next_review_date": "2026-05-08",
    },
    {
        "date": "2026-05-04",
        "project": "Physical Activity Clustering",
        "ml_type": "Unsupervised Learning",
        "topic": "Clustering",
        "algorithm": "K-Means",
        "error_type": "Preprocessing Error",
        "mistake": "Ran K-Means without scaling sensor features.",
        "cause": "K-Means is distance-based, so features with larger scales dominate the clustering result.",
        "fix": "Apply StandardScaler before K-Means; compare silhouette score before and after scaling.",
        "practice_task": "Run K-Means on the same dataset before and after StandardScaler and compare inertia and silhouette score.",
        "status": "Need Practice",
        "difficulty": "Medium",
        "next_review_date": "2026-05-05",
    },
    {
        "date": "2026-05-04",
        "project": "PCA Visualization",
        "ml_type": "Unsupervised Learning",
        "topic": "PCA",
        "algorithm": "PCA",
        "error_type": "Wrong Interpretation",
        "mistake": "Interpreted PC1 and PC2 as if they explained almost all information in the dataset.",
        "cause": "The first two components explained only part of the total variance, so the 2D plot was a simplified view.",
        "fix": "Check explained_variance_ratio_ and cumulative explained variance before making strong conclusions.",
        "practice_task": "Fit PCA and calculate cumulative explained variance for 2, 5, 10 and 20 components.",
        "status": "Need Practice",
        "difficulty": "Medium",
        "next_review_date": "2026-05-06",
    },
    {
        "date": "2026-05-04",
        "project": "Taxi Demand Forecasting",
        "ml_type": "Time Series",
        "topic": "Feature Engineering",
        "algorithm": "pandas rolling",
        "error_type": "Data Leakage",
        "mistake": "Calculated rolling_mean using the current target value.",
        "cause": "The current value should not be used as a feature when forecasting the next step.",
        "fix": "Apply shift() before rolling(): data['rolling_mean'] = data['num_orders'].shift().rolling(window).mean().",
        "practice_task": "Create rolling_mean with and without shift() and explain which version leaks target information.",
        "status": "Need Practice",
        "difficulty": "Hard",
        "next_review_date": "2026-05-05",
    },
    {
        "date": "2026-05-04",
        "project": "Regression Metrics Practice",
        "ml_type": "Supervised Learning",
        "topic": "Metrics",
        "algorithm": "mean_squared_error",
        "error_type": "Wrong RMSE Calculation",
        "mistake": "Reported MSE instead of RMSE in the final conclusion.",
        "cause": "RMSE is the square root of MSE; the metric values have different scales.",
        "fix": "Use rmse = mean_squared_error(y_true, y_pred, squared=False) or sqrt(mean_squared_error(...)).",
        "practice_task": "Calculate MAE, MSE and RMSE manually on a small array and compare the values.",
        "status": "Practiced",
        "difficulty": "Easy",
        "next_review_date": "2026-05-07",
    },
    {
        "date": "2026-05-05",
        "project": "Real Estate Price Prediction",
        "ml_type": "Supervised Learning",
        "topic": "Feature Engineering",
        "algorithm": "pandas / sklearn",
        "error_type": "Target Leakage",
        "mistake": "Included a feature that was calculated after the target event happened.",
        "cause": "The feature would not be available at prediction time, so it makes validation unrealistically good.",
        "fix": "Remove post-event features and keep only information available before prediction.",
        "practice_task": "Review a feature list and mark which features are available before prediction and which cause leakage.",
        "status": "New",
        "difficulty": "Hard",
        "next_review_date": "2026-05-06",
    },
    {
        "date": "2026-05-05",
        "project": "Text Sentiment Classification",
        "ml_type": "NLP",
        "topic": "Text Preprocessing",
        "algorithm": "TfidfVectorizer",
        "error_type": "Preprocessing Error",
        "mistake": "Fitted TfidfVectorizer on the full dataset before validation.",
        "cause": "Vocabulary from the validation/test set leaked into training.",
        "fix": "Fit vectorizer on training text only or use Pipeline with vectorizer and model.",
        "practice_task": "Build a Pipeline with TfidfVectorizer and LogisticRegression, then run cross-validation.",
        "status": "New",
        "difficulty": "Hard",
        "next_review_date": "2026-05-06",
    },
    {
        "date": "2026-05-05",
        "project": "Random Forest Classification",
        "ml_type": "Supervised Learning",
        "topic": "Model Evaluation",
        "algorithm": "RandomForestClassifier",
        "error_type": "Overfitting",
        "mistake": "Compared only train score and did not check validation performance.",
        "cause": "A high train score can hide overfitting and does not prove that the model generalizes well.",
        "fix": "Compare train and validation/test metrics; tune max_depth, min_samples_leaf and n_estimators.",
        "practice_task": "Train a RandomForest with different max_depth values and plot train vs validation F1-score.",
        "status": "Need Practice",
        "difficulty": "Medium",
        "next_review_date": "2026-05-08",
    },
    {
        "date": "2026-05-05",
        "project": "Clustering Evaluation",
        "ml_type": "Unsupervised Learning",
        "topic": "Clustering Metrics",
        "algorithm": "silhouette_score",
        "error_type": "Wrong Interpretation",
        "mistake": "Selected k only by looking at the plot without checking clustering metrics.",
        "cause": "Visual inspection is subjective and can be misleading in high-dimensional data.",
        "fix": "Use elbow method, silhouette score and domain interpretation together.",
        "practice_task": "Calculate silhouette score for k from 2 to 8 and choose a reasonable k with explanation.",
        "status": "New",
        "difficulty": "Medium",
        "next_review_date": "2026-05-09",
    },
    {
        "date": "2026-05-06",
        "project": "Linear Regression Practice",
        "ml_type": "Supervised Learning",
        "topic": "Preprocessing",
        "algorithm": "OneHotEncoder",
        "error_type": "Category Error",
        "mistake": "Got an error when the test set contained an unseen category.",
        "cause": "The encoder was not configured to handle unknown categories.",
        "fix": "Use OneHotEncoder(handle_unknown='ignore') inside a ColumnTransformer/Pipeline.",
        "practice_task": "Build a ColumnTransformer with OneHotEncoder(handle_unknown='ignore') and test it on unseen categories.",
        "status": "New",
        "difficulty": "Medium",
        "next_review_date": "2026-05-09",
    },
    {
        "date": "2026-05-06",
        "project": "Notebook Cleanup",
        "ml_type": "General Python",
        "topic": "Notebook Workflow",
        "algorithm": "Jupyter Notebook",
        "error_type": "Execution Order Error",
        "mistake": "Notebook worked once, but failed after restart because cells were executed out of order.",
        "cause": "Some variables and columns were created in earlier hidden state but not in the final sequential run.",
        "fix": "Restart kernel and run all cells before submission; keep feature creation before model training.",
        "practice_task": "Take one notebook, restart kernel, run all cells, and fix every missing dependency in order.",
        "status": "Need Practice",
        "difficulty": "Easy",
        "next_review_date": "2026-05-07",
    },
    {
        "date": "2026-05-06",
        "project": "Baseline Forecasting",
        "ml_type": "Time Series",
        "topic": "Baseline",
        "algorithm": "Naive Forecast",
        "error_type": "Missing Baseline",
        "mistake": "Evaluated model RMSE without comparing it with a simple baseline.",
        "cause": "Without baseline, it is hard to understand whether the ML model is actually useful.",
        "fix": "Compare model with previous hour/day/week baseline depending on the task.",
        "practice_task": "Create three baselines for time series: previous value, same hour yesterday and same hour last week.",
        "status": "Mastered",
        "difficulty": "Easy",
        "next_review_date": "2026-05-14",
    },
]
